class Need:
    PURPOSE = 'all'
    GENERAL_BROWSING = 'Google'
    GOOGLE = 'Google'
    BOTS = 'BOT'
    SEO = 'SEO'
    SOCIAL_MEDIA_ENGINEERING = 'Social'

class Type:
    HTTP = 'http'
    HTTPS = 'https'
    SOCKS = 'socks'
    SOCKS5 = 'socks5'
    SOCKS4 = 'socks4'
    HTTP_HTTPS = 'http-https'
    CONNECT_25 = 'connect25'
    CONNECT_80 = 'connect80'

class Anonymity:
    ANON = 'all'
    TRANSPARENT = 'TRANSPARENT'
    ANONYMOUS = 'ANONYMOUS'
    ELITE = 'ELITE'
    
class State:
    ALABAMA = 'Alabama'
    ALASKA = 'Alaska'
    ARIZONA = 'Arizona'
    ARKANSAS = 'Arkansas'
    ARMED_FORCES_AFRICA = 'Armed Forces Africa'
    CALIFORNIA = 'California'
    COLORADO = 'Colorado'
    CONNECTICUT = 'Connecticut'
    DELAWARE = 'Delaware'
    DISTRICT_OF_COLUMBIA = 'District of Columbia'
    FLORIDA = 'Florida'
    GEORGIA = 'Georgia'
    HAWAII = 'Hawaii'
    IDAHO = 'Idaho'
    ILLINOIS = 'Illinois'
    INDIANA = 'Indiana'
    IOWA = 'Iowa'
    KANSAS = 'Kansas'
    KENTUCKY = 'Kentucky'
    LOUISIANA = 'Louisiana'
    MAINE = 'Maine'
    MARYLAND = 'Maryland'
    MASSACHUSETTS = 'Massachusetts'
    MICHIGAN = 'Michigan'
    MINNESOTA = 'Minnesota'
    MISSISSIPPI = 'Mississippi'
    MISSOURI = 'Missouri'
    MONTANA = 'Montana'
    NEBRASKA = 'Nebraska'
    NEVADA = 'Nevada'
    NEW_HAMPSHIRE = 'New Hampshire'
    NEW_JERSEY = 'New Jersey'
    NEW_MEXICO = 'New Mexico'
    NEW_YORK = 'New York'
    NORTH_CAROLINA = 'North Carolina'
    NORTH_DAKOTA = 'North Dakota'
    OHIO = 'Ohio'
    OKLAHOMA = 'Oklahoma'
    OREGON = 'Oregon'
    PENNSYLVANIA = 'Pennsylvania'
    RHODE_ISLAND = 'Rhode Island'
    SOUTH_CAROLINA = 'South Carolina'
    SOUTH_DAKOTA = 'South Dakota'
    TENNESSEE = 'Tennessee'
    TEXAS = 'Texas'
    UTAH = 'Utah'
    VERMONT = 'Vermont'
    VIRGINIA = 'Virginia'
    WASHINGTON = 'Washington'
    WEST_VIRGINIA = 'West Virginia'
    WISCONSIN = 'Wisconsin'
    WYOMING = 'Wyoming'

class config:
    type: type = 'all'
    country: str = 'all'
    city: str = 'all'
    state: State = 'all'
    port: str = 'all'
    anonymity: Anonymity = 'all'
    need: Need = 'all'
    page: int = 1
